# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for ShibaClaw Windows .exe (onedir / portable)
#
# Build:
#   pip install -e ".[windows-native,dev]"
#   python scripts/build_windows.py
#
# Output: dist/ShibaClaw/ directory — copy/zip to distribute.

from __future__ import annotations

import sys
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files, collect_dynamic_libs

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

ROOT = Path(SPECPATH)  # noqa: F821  (PyInstaller injects SPECPATH)
SHIBACLAW_PKG = ROOT / "shibaclaw"


def collect_data(src_glob: str, dest_folder: str) -> list[tuple[str, str]]:
    """Return a list of (src_path, dest_folder) tuples for all glob matches."""
    import glob

    pairs = []
    for match in glob.glob(str(ROOT / src_glob), recursive=True):
        p = Path(match)
        if p.is_file():
            pairs.append((str(p), dest_folder))
    return pairs


# ---------------------------------------------------------------------------
# Data files bundled into the .exe directory
# ---------------------------------------------------------------------------

datas = []

# Static WebUI assets
datas += [(str(SHIBACLAW_PKG / "webui" / "static"), "shibaclaw/webui/static")]

# Templates (AGENTS.md, SOUL.md, etc.)
datas += [(str(SHIBACLAW_PKG / "templates"), "shibaclaw/templates")]

# Built-in skills
datas += [(str(SHIBACLAW_PKG / "skills"), "shibaclaw/skills")]

# Default update manifest
datas += [(str(SHIBACLAW_PKG / "updater" / "update_manifest.json"),
           "shibaclaw/updater")]

# Packaged installer script
datas += [(str(ROOT / "scripts" / "install" / "install.ps1"), "scripts/install")]

# Window/tray icons (generated by scripts/generate_icons.py)
datas += collect_data("assets/shibaclaw_*.png", "assets")

_ico = ROOT / "assets" / "shibaclaw.ico"
if _ico.exists():
    datas += [(str(_ico), "assets")]

# Third-party runtime assets (WebView2 DLLs, .NET bridge, CLR loader)
# Explicit collection ensures CI builds bundle these even when
# pyinstaller-hooks-contrib doesn't pick them up automatically.
datas += collect_data_files("webview")
datas += collect_data_files("clr_loader")
datas += collect_data_files("pythonnet")

# ---------------------------------------------------------------------------
# Hidden imports that PyInstaller's static analysis misses
# ---------------------------------------------------------------------------

hiddenimports = [
    # uvicorn internals
    "uvicorn.logging",
    "uvicorn.loops.auto",
    "uvicorn.loops.asyncio",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.http.h11_impl",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.protocols.websockets.websockets_impl",
    "uvicorn.lifespan.on",
    # starlette / anyio
    "starlette.routing",
    "starlette.staticfiles",
    "starlette.middleware.base",
    "anyio",
    "anyio._backends._asyncio",
    # websockets
    "websockets.legacy.client",
    "websockets.legacy.server",
    # pydantic
    "pydantic.deprecated.class_validators",
    # all thinker providers (loaded dynamically by registry)
    "shibaclaw.thinkers.anthropic_provider",
    "shibaclaw.thinkers.openai_provider",
    "shibaclaw.thinkers.azure_openai_provider",
    "shibaclaw.thinkers.custom_provider",
    "shibaclaw.thinkers.github_copilot_provider",
    "shibaclaw.thinkers.openai_codex_provider",
    # integrations (loaded by registry)
    "shibaclaw.integrations.telegram",
    "shibaclaw.integrations.discord",
    "shibaclaw.integrations.slack",
    "shibaclaw.integrations.email",
    "shibaclaw.integrations.matrix",
    "shibaclaw.integrations.wecom",
    "shibaclaw.integrations.dingtalk",
    "shibaclaw.integrations.feishu",
    "shibaclaw.integrations.qq",
    "shibaclaw.integrations.mochat",
    # webview / tray (windows-native extras)
    "webview",
    "webview.platforms.winforms",
    "pystray",
    "pystray._win32",
    "PIL",
    "PIL.Image",
    "pythoncom",
    "win32api",
    "win32con",
    "win32gui",
    # misc
    "tiktoken_ext.openai_public",
    "tiktoken_ext",
    "charset_normalizer",
    "charset_normalizer.md",
    "readability",
    "lxml",
    "lxml._elementpath",
    # .NET bridge (pythonnet / clr_loader)
    "clr",
    "pythonnet",
    "System",
    "System.Drawing",
    "clr_loader",
    "clr_loader.ffi",
    "clr_loader.ffi.coreclr",
    "clr_loader.ffi.mono",
    "clr_loader.ffi.netfx",
    "clr_loader.util",
    "clr_loader.util.find",
    "clr_loader.util.clr_error",
]

# ---------------------------------------------------------------------------
# Binaries to include explicitly (e.g. WebView2 loader DLL if needed)
# ---------------------------------------------------------------------------

binaries = []
binaries += collect_dynamic_libs("webview")
binaries += collect_dynamic_libs("clr_loader")
binaries += collect_dynamic_libs("pythonnet")

# ---------------------------------------------------------------------------
# Analysis
# ---------------------------------------------------------------------------

a = Analysis(  # noqa: F821
    [str(SHIBACLAW_PKG / "desktop" / "__main__.py")],
    pathex=[str(ROOT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[str(ROOT / "pyinstaller-hooks")],
    hooksconfig={},
    runtime_hooks=[str(ROOT / "pyinstaller-hooks" / "rthook_unblock_dlls.py")],
    excludes=["tkinter", "_tkinter"],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)  # noqa: F821

exe = EXE(  # noqa: F821
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="ShibaClaw",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,       # No console window for the desktop build
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ROOT / "assets" / "shibaclaw.ico") if (ROOT / "assets" / "shibaclaw.ico").exists() else None,
)

coll = COLLECT(  # noqa: F821
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="ShibaClaw",
)
